### ISSUE TITLE
Error when switching screens

### ISSUE THREAD

**Issue by silentcicada1** [SebastienGllmt/Anki-Addons#12]
This error occurs without fail on every screen change even when it is the only add on downloaded.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-04-20 10:22:21
Add-ons possibly involved: Throughput Monitor

Caught exception:
Traceback (most recent call last):
  File "aqt/main.py", line 928, in onStudyKey
  File "aqt/main.py", line 591, in moveToState
  File "aqt/gui_hooks.py", line 1538, in __call__
  File "anki/hooks.py", line 611, in runHook
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/826650564/main.py", line 426, in renderProgressBars
    throughput_tracker = GetStateForCol(repaintFormat=True)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/826650564/main.py", line 355, in GetStateForCol
    throughput_tracker.setStudyTimeLeftFormat(throughput[0])
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/826650564/main.py", line 181, in setStudyTimeLeftFormat
    bar_holder.studyTimeLeftBar.progressBar.setMaximum(((seconds_left + self.studyTimeStopwatch.get_time())*granularity) + self.dailyStudyTime)
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647

**Comment by silentcicada1** [comment]
Error also occurs on 2.1.24
